### ISSUE TITLE
Latest Release Causes `futures` package to be included in Python3 installs

### ISSUE THREAD

**Issue by andrewgross** [boto/s3transfer#183] opened 2021-03-18 21:42 UTC
Hey,

You might see some more traffic here soon. It looks like the latest release, `0.3.5` fixed a type in `setup.cfg` that caused the `futures` package to be installed for all installs, not just Python 2.7.  `aws-cli` pins this library to `>=0.3.0, <0.4.0` so new installs will automatically grab this version and error out with something similar to the following.

```
pip, install, awscli) exited with code 1.     ERROR: Command errored out with exit status 1:
     command: /python3/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dv9sw2br/futures/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dv9sw2br/futures/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dv9sw2br/futures/pip-egg-info
         cwd: /tmp/pip-install-dv9sw2br/futures/
    Complete output (4 lines):
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

To fix this issue we had to manually pin `s3transfer==0.3.4` for now. Would be awesome if a fix could be released so installing `s3transfer` on python3 envs works again.

**Comment by andrewgross** [comment] 2021-03-18 21:58
Seems like this may not be present on all versions of python/pip. Had some trouble reproducing across different environments. Will still leave this up if others come across it.

**Comment by nateprewitt** [comment] 2021-03-18 22:14
Hey @andrewgross, thanks for bringing this to our attention! It looks like this is an unintended side effect of this actually. We started building our wheels with a more modern version that includes Wheel Metadata 2.1. The way this setup.py is written is actually incorrect and causing us to include the metadata twice here:

```
Metadata-Version: 2.1
Name: s3transfer
Version: 0.3.5
Summary: An Amazon S3 Transfer Manager
Home-page: https://github.com/boto/s3transfer
Author: Amazon Web Services
Author-email: kyknapp1@gmail.com
License: Apache License 2.0
Platform: UNKNOWN
Classifier: Development Status :: 3 - Alpha
Classifier: Intended Audience :: Developers
Classifier: Natural Language :: English
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Requires-Dist: botocore (<2.0a.0,>=1.12.36)
Requires-Dist: futures (<4.0.0,>=2.2.0)
Requires-Dist: futures (<4.0.0,>=2.2.0) ; python_version=="2.7"
```

We're working on a fix for this now.

**Comment by andrewgross** [comment] 2021-03-18 22:15
Hah! Always fun to see new ways that things can break. Thanks for taking a look!

**Comment by nateprewitt** [comment] 2021-03-18 22:22
Just to head this off as I expect we're going to have some visitors to this issue.

To anyone hitting problems looking for a quick mitigation, this can be resolved for the short term by installing s3transfer==0.3.4 until a new release is out.

**Comment by leenr** [comment] 2021-03-18 23:51
Hi!
Thanks for the quick fix.
Do you plan to [yank](https://pypi.org/help/#yanked) a broken release from PyPI?

**Comment by nateprewitt** [comment] 2021-03-18 23:55
>  Do you plan to yank a broken release from PyPI?

We may, we're still discussing. To be clear, this works on most Python 3 installations. We tried it through most standard distros and weren't able to reproduce. It appears to be an issue with the versions of setuptools/pip being used.

If anyone experiencing this issue can provide info on the following, that'd be super helpful:
```
Python Version: 
Operating System:
Setuptools Version:
Pip Version:
```

**Comment by nateprewitt** [comment] 2021-03-19 01:28
New release has been cut for 0.3.6 which should resolve the issue for those affected.

**Comment by nateprewitt** [comment] 2021-03-19 17:39
Going to resolve this now that things are looking stable. Thanks again, @andrewgross! Let us know if you're still hitting issues.

**Closed by nateprewitt** 2021-03-19 17:39 UTC

**Comment by andrewgross** [comment] 2021-03-19 18:08
Should be all set, thanks again!

Andrew Gross
***@***.***
